### ISSUE TITLE
Compiling under Windows using MSYS2 gcc

### ISSUE THREAD

**Issue by ALewis-GA** [EarthScope/msi#1]
I needed to add "-lregex" to  LDLIBS in src/Makefile  to compile under Windows MSYS2 gcc

**Comment by chad-earthscope** [comment]
Thanks @ALewis-GA.

My inclination now is to change the regex capability to simple globbing wildcards in the next major release, as I don't think most usage actually needs full regex.  This is much more portable and likely sufficient.

**Comment by chad-earthscope** [comment]
As of v4.0 the `-M` and `-R` options are replaced with `-m` and `-r` and are globbing expressions instead of regexes.  

Edit: this now compiles for me under MSYS2 (and Cygwin64) without modification.
